### ISSUE TITLE
Firebase Backend Problem

### ISSUE THREAD

**Issue by abhilasha9920** [dhananjay0610/CoachingClass#1]
Hello Smart GitHub user , this is very nice project.
I have to submit a project like this in my college.
I am not much friendly to firebase firestore. Could you please tell me how can i create backend of firestore and test this project. I hope you will help thanks in advance.

**Comment by dhananjay0610** [comment]
Hey , 
just want to know what do you mean by testing this project?


> Hello Smart GitHub user , this is very nice project.
> I have to submit a project like this in my college.
> I am not much friendly to firebase firestore. Could you please tell me how can i create backend of firestore and test this project. I hope you will help thanks in advance.





Hey , 
just want to know what do you mean by testing this project?
And would like to help you from my side till I  can.

**Comment by dhananjay0610** [comment]
,oo/> Thanks for your reply and also that for you precious time.
> By testinang this project means , I ran this project on emulator but can't go to main activity because of Login Activity.How can I make firestore collections and fields ? Can you provide schema of firestore of this project.
> I hope I am able to explain my problem.




ok. So you tried to run the app from your android studio.
This project uses my account of firebase and it won't work on your android studio because firebase account needs to be connected to the android studio. 
Also just want to know how did you came across this project.

**Comment by abhilasha9920** [comment]
yes you got it correctly. I reached at your project by searching on github.
I will connect my firebase account but i want guidance on creating firestore schema.
Can you provide the screenshot or something like that of your firebase schema.
Thank in advance.

**Comment by dhananjay0610** [comment]
You can mail me or contact by other ways. Because here I will take time to respond.
and sorry for delayed response.
Want to know how much knowledge you have regarding firebase and firestore.

**Comment by abhilasha9920** [comment]
No problem I will wait. I want your help to make firestore collections and fields. I have basic knowledge of firebase. So please upload screenshot of your firestore collections and fields structure.
Thanks for reply.

**Comment by viratraipur** [comment]
@abhilasha9920 Hello abhilasha, I can help you to setup firebase firestore for this project. If you want a better Coaching Institute project you can reply me.

**Comment by abhilasha9920** [comment]
@viratraipur Thank you for showing interest in my issue.
If you want to help me please resolve my queries:
1. Firebase firestore structure.
2. Mai activity gets crash and my device gets switch off every time I open this app.
3. What should be document id in firestore document collection.

I hope that you will help me and resolve my problem.
Thanks again.

**Comment by dhananjay0610** [comment]
hey @abhilasha9920, your app gets crash because your app might not have been connected to your firestore, and also want to ask how to send a screenshot of the firestore collection.

and @viratraipur felt glad that you are interested in this issue. I will also be glad to see your project and also will be happy to see your firestore backend.

**Comment by abhilasha9920** [comment]
@dhananjay0610  thanks for your reply.
You can upload screenshot on project by committing in project directory or you can send screenshot in attachment with reply as I send for demo.
@viratraipur If your project is better than this project please show your project .

**Comment by abhilasha9920** [comment]
![images](https://user-images.githubusercontent.com/70644319/92307268-bb12a580-efb2-11ea-9a40-30fd44614860.png)

**Comment by dhananjay0610** [comment]
this is the sreenshot showing a collection

**Comment by dhananjay0610** [comment]
![Annotation 2020-09-05 204821](https://user-images.githubusercontent.com/45180243/92308173-6f172f00-efb9-11ea-8a69-c1c2e0cf2e6a.jpg)
hjkhjkh

**Comment by abhilasha9920** [comment]
@dhananjay0610 
Thank you for the screenshot. It has helped me very much to understand this project.
But I have still an unsolved query -
is document id is automaticaly generated?

**Comment by abhilasha9920** [comment]
@dhananjay0610 
Is there any admin app?

**Comment by abhilasha9920** [comment]
![xn0n8vkozv551](https://user-images.githubusercontent.com/70644319/92309388-c4a40980-efc2-11ea-94d3-683fbeeaa5ac.jpg)


Can you create structure of the firestore like this.

**Comment by viratraipur** [comment]
@abhilasha9920 i think that @dhananjay0610 has resolved the query you had. So i don't need to explain anything.

@dhananjay0610 I have said my app is better in the sense of backend of my app because it has deployed in web server and written in php sql with web concept and it is easy to understand.

@abhilasha9920 yes it has admin control. You can do the same using web portal provided by us.If you are interested give me your email id to communicate further process.

**Comment by abhilasha9920** [comment]
@viratraipur No my queries has not been solved.

I am not able to setup firebase firestore.
App crashing is going on.

@dhananjay0610 could you please make a demo video of your app or make a tutorial to setup this app.

@viratraipur If you think your app is better than this app, what are you waiting for?
Give me your project source code we want to see that app.

**Comment by dhananjay0610** [comment]
@abhilasha9920  yes, there is an admin app and all the video lectures, quizzes,analysis, and pdfs are organized from the same.

**Comment by dhananjay0610** [comment]
@abhilasha9920  we are two choices :
1) randomly generate  the id of the document 
2) we can set it manually from the code
but the task of generation I mean the first  one is mostly preferred.

**Comment by dhananjay0610** [comment]
yup the demo video is there.

**Comment by dhananjay0610** [comment]
actually, why don't you mail me at dhananjaywaghade06@gmail.com

**Comment by abhilasha9920** [comment]
@dhananjay0610 ok I will mail you to your Gmail account.
Where is demo video and where is the source code of admin app.
I have a question too -"is this a complete code which is uploaded in GitHub?"

**Comment by dhananjay0610** [comment]
yup this is complete code of the app.

**Comment by abhilasha9920** [comment]
@dhananjay0610 I have mailed you at your given email id.
Have you received my email.
If you have not received mail please tell me.

You have not answered all the questions.
Thanks
Further conversation will be in mailbox.

**Comment by dhananjay0610** [comment]
Actually I did not receive any email.

**Comment by abhilasha9920** [comment]
@dhananjay0610 I have mailed you at dhananjaywaghade06@gmail.com , isn't it your email address.
You can contact me on my email address-
abhilasha9920@hotmail.com

**Comment by viratraipur** [comment]
@abhilasha9920  I can't send you source code because it is not free of cost. You have to purchase it.
But, If you want the demo video of app , I can send it in your email account (abhilasha9920@hotmail.com).

**Comment by abhilasha9920** [comment]
@viratraipur ok send me the demo video?
Literally I don't want to purchase anything.
By the way,
What is the price of the source code?

**Comment by viratraipur** [comment]
@abhilasha9920 I have sent you the Demo Video link in your mailbox abhilasha9920@hotmail.com 
If you have not received, Inform me.
You will not deny to purchase code after watching demo video.
And
The price of the Source Code is less than 1000 INR as per your demand(may vary).
If you want only minimal features that is mentioned in video the price is minimal.
So don't think about money, the price negligible.
Just think once about your project.

**Comment by abhilasha9920** [comment]
@viratraipur  I am waiting for @dhananjay0610 to give the solution. But if he doesn't help, I will purchase your source code because your project is also awesome.
And it can also be deployed for small business.
Great work @viratraipur .
But want to talk personally.Please come in mailbox.

**Comment by abhilasha9920** [comment]
@dhananjay0610 You have not replied my email.
May be you have not got the email , If you have not got ,tell me to resend in GitHub.
And 
In case you got the email and you have not replied , It seems that you are not interested to help me or you are ignoring that.
You can simply deny to help me if you don't want to help or you don't have time because i don't want to disturb you doing multiple mails.So , what's on your mind, you can elaborate.

**Comment by abhilasha9920** [comment]
@viratraipur Ok done I will purchase your code.
Let's talk in mailbox.

Thanks mr @dhananjay0610 for the help.
